<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOTxkJYu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOTxkJYu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOTxkJYu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOTxkJYu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOTxkJYu\App_KernelDevDebugContainer([
    'container.build_hash' => 'OTxkJYu',
    'container.build_id' => '9347392f',
    'container.build_time' => 1674679963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOTxkJYu');
